index:
    path: /
    controller: App\Controller\HomeController::index

listSubscriptions:
    path: /subscriptions
    methods: GET
    controller: App\Controller\SubscriptionController::list

addSubscriptions:
    path: /subscription
    methods: POST
    controller: App\Controller\SubscriptionController::add

updateSubscription:
    path: /subscription/{id}
    methods: PUT
    controller: App\Controller\SubscriptionController::update

listPaymentTypes:
    path: /paymentTypes
    methods: GET
    controller: App\Controller\PaymentTypeController::list

createPaymentType:
    path: /paymentType
    methods: POST
    controller: App\Controller\PaymentTypeController::create

readPaymentType:
    path: /paymentType
    methods: GET
    controller: App\Controller\PaymentTypeController::read

updatePaymentType:
    path: /paymentType/{id}
    methods: PUT
    controller: App\Controller\PaymentTypeController::update

deletePaymentType:
    path: /paymentType
    methods: DELETE
    controller: App\Controller\PaymentTypeController::delete